[tool.poetry]
name = "mcode-linear"
version = "0.1.0"
description = ""
authors = ["Jaakko Rantala <jaakko.rantala@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
